# @package _global_

dataset_name: ps_male_3

model:
  gaussian:
    near: 0.01

dataset:
  name: people_snapshot
  root_dir: "data/data_prepared"
  subject: male-3-casual

  train_frames: [ 0, 456, 4 ]
  # train_frames: [ 0, 456, 400 ]
  val_frames: [ 456, 457, 4 ]
  test_frames:
    pose: [ 456, 676, 4 ]
    all: [ 0, 676, 1 ]
  predict_frames: [0, 0, 1]

  img_hw:
    - 540
    - 540

  resolution: -1
  white_background: false
  data_device: cuda
  eval: false
  disable_filter3D: true